import React from 'react';
import { Container } from 'react-bootstrap';

export default function Deals() {
    const bgImg={ width:"100%", height:"500px"}

    return (
        <div>
            <Container style={{marginTop:"8%"}}><h3 className="entry-title" style={{color:"#00d369f6"}}>Dealing with Customers</h3>
            <img src="https://cdn57.androidauthority.net/wp-content/uploads/2020/08/Samsung-Galaxy-Note-20-Ultra-screen-straight-on-close-1.jpg" alt="" style={bgImg}/>
                <div className="post-main"><header className="entry-header stick"></header><div className="entry-content"><p>Your company’s most vital asset is its customers, so you need to make sure you’re dealing with your customers properly. Without them, you would not, and could not, exist in business. Sure, you can attract new customers with unique products, free gifts, or reducing your prices; but if you’re not creating relationships with them, they’re not going to return or recommend you.</p><p>Sometimes it can be challenging to build those relationships. The questions you get asked in a customer facing role can be in equal parts interesting, monotonous, funny and challenging. The key is to make each customer feel welcome and helped.</p><p>Here are ten tips for dealing with customers and delivering excellent customer service:</p><h5>1. Listen to Customers</h5><p>Sometimes, customers just need to know that you’re listening. If they’re confused or have a problem, by lending a listening ear, you’re showing that you care and that you’re not dismissing them.</p><h5>2. Apologize</h5><p>When something goes wrong, apologize. It’s amazing how calming the words “I’m sorry” can be. Don’t engage in fault-finding or laying blame, but let them know you’re sorry they had a problem. Deal with the problem immediately and let the customer know what you have done.</p><h5>3. Take Them Seriously</h5><p>Make customers feel important and appreciated. No matter how ridiculous a question may sound to you; it’s important to the customer. If they feel like they’re being laughed at, or spoken down to, they will not purchase anything. Customers can be very 
                    sensitive and will know whether or not you really care about them.</p><h5>4. Stay Calm</h5><p>Difficult as it is sometimes, it is important to stay calm. Your calming approach will help your customer stay calm too. They will feel like you’re in control of the situation and that you can help solve their problem.</p><h5>5. Identify and Anticipate Needs</h5><p>Most customer needs are emotional rather than logical. The more you know your customers, the better you become at anticipating their needs. Communicate regularly so that you’re aware of problems or upcoming needs.</p><h5>6. Suggest Solutions</h5><p>Have a menu of calming remedies which you and your employees can use. Whether it’s purely a refund or return, or if it’s coupons or a free service. By agreeing in advance the scenarios where you will provide these remedies, and how much you’re willing to spend, you will be able to speak calmer and more confidently when offering the solution.</p><h5>7. Appreciate the Power of “Yes”</h5><p>Always look for ways to help your customers. When they have a request (as long as it is reasonable) tell them that you can do it. Figure out how afterwards. Look for ways to make doing business with you easy. Always do what you say you’re going to do.</p><h5>8. Acknowledge Your Limits</h5>
                <p>Yes is a powerful word but if you’re unable to fulfil a request: know your limits. You can’t be everything to everyone. If you don’t think you can fulfil the request, help them find an alternate remedy. Whether that remedy is your business or another, they will appreciate the extra mile you went to help them, and will recommend your business to their network.</p><h5>9. Be Available</h5><p>Customer service is no longer just about face-to-face contact and telephone. If you’re working in an industry or marketplace where customers are constantly online, you need to amend your service delivery to incorporate that. It does not need to be a dedicated <a href="http://mashable.com/2009/05/09/twitter-customer-service/">helpdesk Twitter handle</a>, simply make sure you respond promptly and informatively to clients on your main business Facebook page or to your Twitter account.</p><h5>10. Get Regular Feedback</h5><p>Feedback is a great way to grow both your business and your skills. Provide ways for customers to give feedback, whether it’s a follow up email or phone call, a suggestions box or something more fun and innovative.</p><h5><strong>Here to Help </strong></h5><p>No matter what stage of your business journey you’re at, Small Business BC has the resources you need to succeed. Check out our range of <a href="https://smallbusinessbc.ca/education/">business webinars</a>, our <a href="https://smallbusinessbc.ca/advisory/talk-to-an-expert-series/">Talk to an Expert Advisories</a>, or browse our selection of <a href="https://smallbusinessbc.ca/articles/">business articles</a>.</p><p>&nbsp;</p></div><div className="accordion"></div><div className="entry-meta"></div><div className="share-buttons block"><div className="content-social"><div className="share-buttons">
                <a target="_blank" className="mr-3 mr-md-0 ml-md-4 share-button share-facebook" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fsmallbusinessbc.ca%2Farticle%2Ften-tips-dealing-customers%2F" title="Share on Facebook"><span className="share-facebook"></span></a>
                <a target="_blank" className="mr-3 mr-md-0 ml-md-4 share-button share-twitter" href="https://twitter.com/intent/tweet?url=https%3A%2F%2Fsmallbusinessbc.ca%2Farticle%2Ften-tips-dealing-customers%2F&amp;text=10 Tips for Dealing with Customers&amp;via=" title="Tweet this"><span className="share-twitter"></span></a>
                <a target="_blank" className="mr-3 mr-md-0 ml-md-4 share-button share-linkedin" href="https://www.linkedin.com/shareArticle?mini=true&amp;url=https%3A%2F%2Fsmallbusinessbc.ca%2Farticle%2Ften-tips-dealing-customers%2F&amp;title=10+Tips+for+Dealing+with+Customers" title="Share on LinkedIn"><span className="share-linkedin"></span></a></div></div></div></div>
            </Container>
        </div>
    );
};
